{{- if .Values.cases.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-chaos-test-case
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      initContainers:
        - name: wait-tiflow-cluster
          image: busybox
          command: ['sh', '-c', 'sleep 60']
      containers:
        - name: chaos-test-case
          image: dataflow:chaos
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - "/tiflow-chaos-case"
            - "--duration=20m"
            - "--etcd-addr={{ include "tiflow.name" . }}-metastore-business:12479"
            - "--master-addr={{ include "tiflow.name" . }}-server-master:10240"
            - "--master-count={{ .Values.master.replicas }}"
            - "--worker-count={{ .Values.executor.replicas }}"
      restartPolicy: Never
  backoffLimit: 0 # fail immediately
{{- end -}}