apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiflow.name" . }}-executor
  labels:
    app: {{ include "tiflow.name" . }}-executor
spec:
  ports:
    - name: {{ include "tiflow.name" . }}-executor
      port: 10241
      targetPort: 10241
  selector:
    app: {{ include "tiflow.name" . }}-executor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tiflow.name" . }}-executor
  labels:
    app: {{ include "tiflow.name" . }}-executor
spec:
  selector:
    matchLabels:
      app: {{ include "tiflow.name" . }}-executor
  serviceName: {{ include "tiflow.name" . }}-executor
  replicas: {{ .Values.executor.replicas }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ include "tiflow.name" . }}-executor
    spec:
      initContainers:
        - name: wait-server-master
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ include "tiflow.name" . }}-server-master; do echo waiting for server master; sleep 2; done;']
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
      containers:
        - name: {{ include "tiflow.name" . }}-executor
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          volumeMounts:
            - mountPath: /log
              name: log
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_SERVICE_NAME
              value: {{ include "tiflow.name" . }}-executor
          ports:
            - containerPort: 10241
              name: executor
          command:
            - "/tiflow"
            - "executor"
            - "--name=$(MY_POD_NAME)"
            - "--worker-addr=0.0.0.0:10241"
            - "--advertise-addr=$(MY_POD_NAME).$(MY_SERVICE_NAME).$(MY_POD_NAMESPACE):10241"
            - "--join={{ include "tiflow.masterAddr" . }}"
            - "--config=/conf/executor.toml"
            - "--log-file=/log/$(MY_POD_NAME).log"
  volumeClaimTemplates:
    - metadata:
        name: log
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.executor.logStorage }}
