name: dataflow engine image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build-engine
        run: docker build -f ./deployments/engine/docker/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pingcap
          password: ${{ secrets.DOCKERHUB }}

      - name: Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pingcap/tiflow:latest
