name: dataflow engine image

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build-engine
        run: docker build -f ./deployments/engine/docker/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pingcap
          password: ${{ secrets.DOCKERHUB }}

      - name: Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pingcap/tiflow:latest
